Repository Board-We/backend, pull requests merged in 2022-12, with the labels that each got.

#2 [feat] 영진 담당 기능 구현 (작업 중)
  src/main/java/com/boardwe/boardwe/controller/BoardCreateController.java
  src/main/java/com/boardwe/boardwe/controller/BoardDeleteController.java
  src/main/java/com/boardwe/boardwe/controller/BoardMemoSearchController.java
  src/main/java/com/boardwe/boardwe/controller/MemoAddController.java
  src/main/java/com/boardwe/boardwe/controller/MemoDeleteController.java
  src/main/java/com/boardwe/boardwe/dto/BoardCreateRequestDto.java
  src/main/java/com/boardwe/boardwe/dto/BoardCreateResponseDto.java
  src/main/java/com/boardwe/boardwe/dto/BoardDeleteRequestDto.java
  src/main/java/com/boardwe/boardwe/dto/BoardMemoSearchResponseDto.java
  src/main/java/com/boardwe/boardwe/dto/MemoAddRequestDto.java
  src/main/java/com/boardwe/boardwe/dto/MemoAddResponseDto.java
  src/main/java/com/boardwe/boardwe/dto/MemoDeleteRequestDto.java
  src/main/java/com/boardwe/boardwe/dto/ResponseDto.java
  src/main/java/com/boardwe/boardwe/dto/inner/BoardCreateThemeRequestDto.java
  src/main/java/com/boardwe/boardwe/dto/inner/BoardThemeSearchResponseDto.java
  src/main/java/com/boardwe/boardwe/dto/inner/MemoBackgroundTextColorSetsRequestDto.java
  src/main/java/com/boardwe/boardwe/dto/inner/MemoImagesTextColorSetsRequestDto.java
  src/main/java/com/boardwe/boardwe/dto/inner/MemoSearchResponseDto.java
  src/main/java/com/boardwe/boardwe/dto/inner/MemoThemesWithIdResponseDto.java
  src/main/java/com/boardwe/boardwe/exception/ErrorCode.java
  src/main/java/com/boardwe/boardwe/exception/custom/BoardThemeNotFoundException.java
  src/main/java/com/boardwe/boardwe/exception/custom/CannotStoreFileException.java
  src/main/java/com/boardwe/boardwe/exception/custom/MemoNotFoundException.java
  src/main/java/com/boardwe/boardwe/exception/custom/MemoThemeNotFoundException.java
  src/main/java/com/boardwe/boardwe/exception/custom/MemoWithInvalidBoardException.java
  src/main/java/com/boardwe/boardwe/exception/custom/UnableToCreateDirectoryException.java
  src/main/java/com/boardwe/boardwe/repository/BoardRepository.java
  src/main/java/com/boardwe/boardwe/repository/MemoRepository.java
  src/main/java/com/boardwe/boardwe/repository/MemoThemeRepository.java
  src/main/java/com/boardwe/boardwe/repository/TagRepository.java
  src/main/java/com/boardwe/boardwe/service/BoardCreateService.java
  src/main/java/com/boardwe/boardwe/service/BoardDeleteService.java
  src/main/java/com/boardwe/boardwe/service/BoardMemoSearchService.java
  src/main/java/com/boardwe/boardwe/service/MemoAddService.java
  src/main/java/com/boardwe/boardwe/service/MemoDeleteService.java
  src/main/java/com/boardwe/boardwe/service/impl/BoardCreateServiceImpl.java
  src/main/java/com/boardwe/boardwe/service/impl/BoardDeleteServiceImpl.java
  src/main/java/com/boardwe/boardwe/service/impl/BoardMemoSearchServiceImpl.java
  src/main/java/com/boardwe/boardwe/service/impl/MemoAddServiceImpl.java
  src/main/java/com/boardwe/boardwe/service/impl/MemoDeleteServiceImpl.java
Labels: feature

#3 [feat] 현우 담당 기능 구현 (작업 중)
  src/main/java/com/boardwe/boardwe/controller/BoardListSelectController.java
  src/main/java/com/boardwe/boardwe/controller/BoardSearchController.java
  src/main/java/com/boardwe/boardwe/controller/WelcomeBoardController.java
  src/main/java/com/boardwe/boardwe/dto/BoardSearchDto.java
  src/main/java/com/boardwe/boardwe/dto/ListElementDtos/MemoThemeResponseDto.java
  src/main/java/com/boardwe/boardwe/dto/ListElementDtos/SimpleBoardResponseDto.java
  src/main/java/com/boardwe/boardwe/dto/ListElementDtos/ThemeResponseDto.java
  src/main/java/com/boardwe/boardwe/dto/WelcomeBoardResponseDto.java
  src/main/java/com/boardwe/boardwe/repository/BoardRepository.java
  src/main/java/com/boardwe/boardwe/repository/BoardThemeRepository.java
  src/main/java/com/boardwe/boardwe/repository/MemoRepository.java
  src/main/java/com/boardwe/boardwe/repository/MemoThemeRepository.java
  src/main/java/com/boardwe/boardwe/repository/TagRepository.java
  src/main/java/com/boardwe/boardwe/repository/ThemeCategoryRepository.java
  src/main/java/com/boardwe/boardwe/service/BoardSearchService.java
  src/main/java/com/boardwe/boardwe/service/HotBoardListSelectService.java
  src/main/java/com/boardwe/boardwe/service/RecommendBoardListSelectService.java
  src/main/java/com/boardwe/boardwe/service/WelcomeBoardService.java
  src/main/java/com/boardwe/boardwe/service/impl/BoardSearchServiceImpl.java
  src/main/java/com/boardwe/boardwe/service/impl/HotBoardListServiceImpl.java
  src/main/java/com/boardwe/boardwe/service/impl/RecommendBoardListServiceImpl.java
  src/main/java/com/boardwe/boardwe/service/impl/WelcomeBoardServiceImpl.java
  src/test/java/com/boardwe/boardwe/service/impl/FileServiceImplTest.java
Labels: feature

#7 Bugfix/invalid page param in search board
  src/main/java/com/boardwe/boardwe/entity/Board.java
  src/main/java/com/boardwe/boardwe/service/impl/BoardSearchServiceImpl.java
  src/main/java/com/boardwe/boardwe/service/impl/BoardServiceImpl.java
Labels: bug, feature

#9 [chore] 보드 테마 관련 응답 형식 수정, 보드 조회&보드 대문 API 통합, 이미지 url 형식 수정
  src/main/java/com/boardwe/boardwe/config/ImageConfig.java
  src/main/java/com/boardwe/boardwe/controller/BoardController.java
  src/main/java/com/boardwe/boardwe/dto/req/BoardCreateRequestDto.java
  src/main/java/com/boardwe/boardwe/dto/req/inner/BoardThemeCreateRequestDto.java
  src/main/java/com/boardwe/boardwe/dto/req/inner/MemoColorAndTextColorRequestDto.java
  src/main/java/com/boardwe/boardwe/dto/req/inner/MemoThemesCreateRequestDto.java
  src/main/java/com/boardwe/boardwe/dto/res/BoardReadResponseDto.java
  src/main/java/com/boardwe/boardwe/dto/res/BoardSearchResponseDto.java
  src/main/java/com/boardwe/boardwe/entity/InitDb.java
  src/main/java/com/boardwe/boardwe/exception/ErrorCode.java
  src/main/java/com/boardwe/boardwe/exception/custom/other/InvalidMemoThemeListException.java
  src/main/java/com/boardwe/boardwe/service/BoardSearchService.java
  src/main/java/com/boardwe/boardwe/service/BoardService.java
  src/main/java/com/boardwe/boardwe/service/impl/BoardSearchServiceImpl.java
  src/main/java/com/boardwe/boardwe/service/impl/BoardServiceImpl.java
  src/main/java/com/boardwe/boardwe/util/impl/BoardInfoUtilImpl.java
  src/main/java/com/boardwe/boardwe/util/impl/ThemeUtilImpl.java
  src/main/resources/application.yml
  src/test/java/com/boardwe/boardwe/service/impl/BoardReadTest.java
Labels: chore

#8 [bugfix] 검색 시 public보드만 검색
  src/main/java/com/boardwe/boardwe/repository/BoardRepository.java
Labels: bug

#10 [feat] Memo list 조회기능 추가
  src/main/java/com/boardwe/boardwe/controller/BoardController.java
  src/main/java/com/boardwe/boardwe/controller/MemoController.java
  src/main/java/com/boardwe/boardwe/dto/res/BoardReadResponseDto.java
  src/main/java/com/boardwe/boardwe/dto/res/MemoSearchResponseDto.java
  src/main/java/com/boardwe/boardwe/dto/res/MemoSelectResponseDto.java
  src/main/java/com/boardwe/boardwe/dto/res/WelcomeBoardResponseDto.java
  src/main/java/com/boardwe/boardwe/exception/ErrorCode.java
  src/main/java/com/boardwe/boardwe/exception/custom/other/BoardWritingException.java
  src/main/java/com/boardwe/boardwe/exception/custom/other/InvalidPasswordException.java
  src/main/java/com/boardwe/boardwe/service/BoardService.java
  src/main/java/com/boardwe/boardwe/service/MemoService.java
  src/main/java/com/boardwe/boardwe/service/impl/BoardServiceImpl.java
  src/main/java/com/boardwe/boardwe/service/impl/MemoServiceImpl.java
Labels: feature

#12 [chore] 메모 리스트 조회 API 응답에 메모 아이디 추가
  src/main/java/com/boardwe/boardwe/dto/res/MemoSelectResponseDto.java
  src/main/java/com/boardwe/boardwe/service/impl/BoardServiceImpl.java
  src/main/java/com/boardwe/boardwe/service/impl/MemoServiceImpl.java
Labels: chore

#14 Test/board search service
  src/test/java/com/boardwe/boardwe/service/impl/BoardSearchServiceImplTest.java
Labels: test

#13 Board create test
  src/main/java/com/boardwe/boardwe/dto/req/BoardCreateRequestDto.java
  src/main/java/com/boardwe/boardwe/dto/req/inner/MemoThemesCreateRequestDto.java
  src/test/java/com/boardwe/boardwe/service/impl/BoardCreateTest.java
  src/test/resources/files/imageBase64Test.txt
Labels: test

#16 [feat] MySQL 연결 및 docker 설정
  Dockerfile
  build.gradle
  docker-compose/backend-docker-compose-only-db.yml
  docker-compose/backend-docker-compose.yml
  docker-compose/mysql/Dockerfile
  docker-compose/mysql/conf.d/my.cnf
  docker-compose/mysql/initdb.d/1.create_database.sql
  docker-compose/mysql/initdb.d/2.create_table.sql
  files/testImage.jpg
  init_sql.sql
  src/main/java/com/boardwe/boardwe/config/ImageConfig.java
  src/main/java/com/boardwe/boardwe/config/LogAspect.java
  src/main/java/com/boardwe/boardwe/config/LogInterceptor.java
  src/main/java/com/boardwe/boardwe/entity/Board.java
  src/main/java/com/boardwe/boardwe/entity/BoardTheme.java
  src/main/java/com/boardwe/boardwe/entity/ImageInfo.java
  src/main/java/com/boardwe/boardwe/entity/InitDb.java
  src/main/java/com/boardwe/boardwe/entity/Memo.java
  src/main/java/com/boardwe/boardwe/entity/MemoTheme.java
  src/main/java/com/boardwe/boardwe/entity/Tag.java
  src/main/java/com/boardwe/boardwe/entity/ThemeCategory.java
  src/main/java/com/boardwe/boardwe/exception/ControllerExceptionHandler.java
  src/main/java/com/boardwe/boardwe/repository/BoardRepository.java
  src/main/resources/application.yml
Labels: feature

#17 [chore] DB 이미지에 데이터 insert 쿼리 추가
  docker-compose/mysql/Dockerfile
  docker-compose/mysql/initdb.d/2.create_table.sql
  docker-compose/mysql/initdb.d/3.insert_data.sql
Labels: chore

#15 [bugfix] 보드 삭제 & 메모 붙이기 Unit Test
  files/imageBase64Test.txt
  src/main/java/com/boardwe/boardwe/dto/req/BoardDeleteRequestDto.java
  src/main/java/com/boardwe/boardwe/dto/req/MemoCreateRequestDto.java
  src/main/java/com/boardwe/boardwe/dto/req/MemoDeleteRequestDto.java
  src/test/java/com/boardwe/boardwe/service/impl/BoardDeleteTest.java
  src/test/java/com/boardwe/boardwe/service/impl/CreateMemoTest.java
  src/test/java/com/boardwe/boardwe/service/impl/DeleteMemoTest.java
Labels: test
