Repository Board-We/backend, pull requests merged in 2023-01, with the labels that each got.

#19 [chore] 로그 설정
  build.gradle
  src/main/java/com/boardwe/boardwe/config/LogInterceptor.java
  src/main/java/com/boardwe/boardwe/config/WebConfig.java
  src/main/java/com/boardwe/boardwe/exception/ControllerExceptionHandler.java
  src/main/java/com/boardwe/boardwe/exception/ErrorResponseDto.java
  src/main/java/com/boardwe/boardwe/service/impl/BoardSearchServiceImpl.java
  src/main/java/com/boardwe/boardwe/service/impl/BoardServiceImpl.java
  src/main/java/com/boardwe/boardwe/service/impl/FileServiceImpl.java
  src/main/java/com/boardwe/boardwe/service/impl/MemoServiceImpl.java
  src/main/java/com/boardwe/boardwe/service/impl/ThemeServiceImpl.java
  src/main/java/com/boardwe/boardwe/util/impl/FileUtilImpl.java
  src/main/java/com/boardwe/boardwe/util/impl/ThemeUtilImpl.java
  src/main/resources/application.yml
  src/main/resources/log4j2-dev.xml
  src/main/resources/log4j2-prod.xml
  src/test/java/com/boardwe/boardwe/service/impl/DeleteMemoTest.java
  src/test/resources/files/imageBase64Test.txt
Labels: chore

#21 Feat/search board
  src/main/java/com/boardwe/boardwe/dto/res/BoardSearchResponseDto.java
  src/main/java/com/boardwe/boardwe/service/BoardSearchService.java
  src/main/java/com/boardwe/boardwe/service/impl/BoardSearchServiceImpl.java
  src/test/java/com/boardwe/boardwe/service/impl/BoardSearchServiceImplTest.java
  src/test/java/com/boardwe/boardwe/service/impl/CreateMemoTest.java
Labels: chore

#22 [feat] AWS 자동 배포 설정 추가
  .github/workflows/deploy.yaml
  build.gradle
  src/main/resources/application.yml
Labels: feature

#23 [chore] Github Action이 실행할 배포 스크립트 추가
  .github/workflows/deploy.yaml
  appspec.yml
  scripts/gh_deploy.sh
Labels: chore

#18 [test] 메모 삭제 기능 & 보드 내 메모 검색 기능 & 메모 리스트 조회 기능 단위테스트
  src/test/java/com/boardwe/boardwe/service/impl/BoardCreateTest.java
  src/test/java/com/boardwe/boardwe/service/impl/DeleteMemoTest.java
  src/test/java/com/boardwe/boardwe/service/impl/MemoSearchInBoardTest.java
  src/test/java/com/boardwe/boardwe/service/impl/SearchMemoListTest.java
Labels: test
